### ISSUE TITLE
[BUG] Generated code not marked as auto-generated (not excluded from code-analysis)

### ISSUE THREAD

**Issue by hakenr** [reactiveui/refit#1095]
SYMPTOM
Generated code violates StyleCop rule SA1517:CodeMustNotContainBlankLinesAtStartOfFile.

CAUSE
The `#pragma warning disable` currently used is not enough.
You should use `// <auto-generated />` or other official generated code markers to prevent code-analysis of generated code.

**Comment by clairernovotny** [comment]
StyleCop is suposed to ignore files with `.g.cs`.  @sharwell .

**Comment by sharwell** [comment]
All generated code should have the following in a comment at the top of the file:

```
/// <auto-generated/>
```

For compatibility with the legacy WinForms designer, StyleCop Analyzers 1.0 did not require files ending with **.Designer.cs** to include this comment. The same exception was _not_ made for **.g.cs** because the XAML compiler _did_ emit the expected comment.

Starting with StyleCop Analyzers 1.1, the designation of generated code was deferred to Roslyn itself. The Roslyn semantics for marking a file as generated when it fails to include the expected comment are implemented here:

https://github.com/dotnet/roslyn/blob/d1adf48a74f06dab2a7d6d7b8ac57299d707bf54/src/Compilers/Core/Portable/InternalUtilities/GeneratedCodeUtilities.cs#L61-L86
