### ISSUE TITLE
Support for abstract class

### ISSUE THREAD

**Issue by mr5z** [reactiveui/refit#1154]
https://github.com/reactiveui/refit/blob/0baec2ea6f462264696fe476a88dfc267b527ad7/Refit/RequestBuilderImplementation.cs#L48

Hello!

Consider this case, I have a Solution which contains the following: WebAPI, AuthServer, Xamarin Forms, Shared Library, etc...
The simplification of my current structure looks like below:
```
[+] Shared
    - IProductProvider
[+] Mobile
    - ProductRepository : IProductProvider
[+] WebApi
    - ProductController : IProductProvider
```

The Mobile would use the API controllers provided by WebApi (ASP MVC). Mobile and WebApi must comply to IProductProvider provided by Shared. Since I would like to use Refit, I would need to convert the Mobile's ProductRepository to IProductRepository (DAO). Now, C# doesn't support "interface implements interface" and all I could think of is making it an abstract but isn't supported by Refit also. I am running out of ideas at the moment. Can abstract class be supported in Refit?

**Comment by james-s-tayler** [comment]
I think the semantics of an abstract class are a bit too loose compared to that of an interface, so my first inclination wouldn't be to add support (and complexity) for that. Rather in this particular case if I were developing a project that worked like that I would have ProductRepository wire in a Refit client that ProductRepository simply delegated the calls to.

**Comment by clairernovotny** [comment]
Abstract classes cannot be supported as Refit generates an implementation class. I would recommend defining your API interfaces separately from your controller.

**Comment by 82amp** [comment]
I know this issue is closed, but I hope this still gets seen by the team.

I think there is a use case for supporting generation of implementation class against an abstract base class instead of an interface. Interfaces are meant to be pure and implementation agnostic. By requiring [Attributes] for specifying metadata about the request, it ties the implementation of the interface to Refit. Whilst it would be possible to follow other patterns to reduce the direct dependency on Refit, that requires a lot of boilerplate code to serve a fairly simple purpose.

Consider the following:
```
public interface IFooClient {
   public Task<ReturnType> Get(int id, string search);
}

public abstract class FooClient : IFooClient {
   public abstract Task<ReturnType> Get([Query]int id, [Query]string search);
}
```
Using DI, I could inject the concrete implementation of FooClient (lets call that GeneratedFooClient) into something that expects an IFooClient. This means that my consumption of IFooClient can be completely agnostic to implementation, and I can share IFooClient, swap out Refit, etc., without worrying about the underlying implementation

**Comment by msmolka** [comment]
I just wonder, based on implementation. Why code is bothering about checking if type is interface?  Abstract methods in abstract class would work as well. Maybe less coupled implication with abstraction would be better? Or at least give such option?

any way, code is only looking for methods with attributes, so any other interface method would be ignored. 

If you want you can only check abstract methods of abstract classes.

**Comment by odinnou** [comment]
Hello, we are building an application based on the hexagonal architecture, we were conscidering to not use Refit because of that.
Indeed, the `port` (interfaces), present in the `Core / Business` should be agnostic of any framework.

**But**, we decide to stick with it because of its multiple pros over its alternatives, pragmatism wins.

**Comment by clairernovotny** [comment]
I don't see Refit ever supporting abstract base classes. We do support Default Interface Methods, however, which allows some logic to live in an interface and be overridden by an implementing class.

**Comment by msmolka** [comment]
The problem is opposite. Because Refit is using interfaces which are abstractions and cannot be overwritten. Which leads to separation problem. You cannot design abstraction interfaces that would be used by refit and domain or any other HttpClient implementation.  Which leads to some DRY issues. 

The only way to solve the problem is to manually duplicate
a) one for interaction
b) one for abstraction

which can be dangerous, because person implementing feature needs to be sure that internal interface Refit duplication supports all abstraction changes.
