### ISSUE TITLE
Question: Does refit support the use of scrutor..

### ISSUE THREAD

**Issue by ekjuanrejon** [reactiveui/refit#1203]
I have a refit web client that is working fine. I want to use a decorator with Scrutor. Does refit support a decorator?

**Comment by lostincomputer** [comment]
What do you want to do with it?

**Comment by ekjuanrejon** [comment]
So I have an a public api. This api call an internal search service. This call is an http call and is done with refit. So what I want to do is intercept the request and attach certain claim based on the user that is logged in..

**Comment by lostincomputer** [comment]
Refit doesn't need to support decorators because that's not how decorators work. The interface that gets decorated doesn't need to be aware that it's decorated. In other words, Scrutor works on any interface.

There are multiple ways to intercept the request beside creating a decorator. The most common way is by creating a `DelegatingHandlers`.
