### ISSUE TITLE
Feature request - custom response deserialization

### ISSUE THREAD

**Issue by thefex** [reactiveui/refit#226]
As in title.

**Comment by thefex** [comment]
Check my PR, please.

**Comment by bennor** [comment]
You can do this right already using a return type of `Task<HttpContent>`, where you provide your own implementation of `HttpContent` for custom deserialization.

**Comment by thefex** [comment]
Using a return type of "Task<HttpContent>" - you mean return in interfaces? That would really suck - people use Refit because it is strongly typed.

**Comment by bennor** [comment]
Not `Task` -- `Task<HttpContent>`, where the `HttpContent` can be anything that derives from it. e.g. `Task<XmlContent<SomeObject>>` where `XmlContent<T>` is a custom deserializer that implicitly casts to `T`.

Still strong typed, and all built on the existing implementation -- but perhaps a bit more complicated.

There might still be a benefit in having a custom deserializer there. Up to @paulcbetts really. It doesn't add much complexity.

The other changes in the PR - upgrading the project type to Windows 8.1 - should be a separate PR and may be a breaking change.

**Comment by dlprows** [comment]
When i tried this it doesn't work.
The code you referenced is doing strict `==` equality on the types, so unless you use `Task<HttpContent>` or `Task<HttpResponseMessage>` it will try to feed it through the json deserializer. 
Subclasses of `HttpContent` or `HttpResponseMessage` go through the json deserializer because they are not strictly equal to `HttpContent` or `HttpResponseMessage`, they're subclasses.

I think the code referenced would need to be 
```var returnType = restMethod.SerializedReturnType;
var httpContentType = typeof(HttpContent);
if(returnType == httpContentType || returnType.IsSubclassOf(httpContentType)) 
```
both at the line referenced, and a few lines higher for the `HttpResponseMessage` in order for it to work the way you described.

Also, one problem with implicit casting as suggested is that an implicit cast can't be async, and it seems like a bad idea to have all those `async`/`await`s be run synchronously in an implicit cast.

Any suggestions on how to proceed?

**Comment by bennor** [comment]
Yeah, sorry -- you're right. Looks like I was wrong about `HttpContent`.

I'm not sure how implicit casting not being async could be a problem. You'd need to give an example. But I don't know if it's relevant since you can't use something that derives from HttpContent anyway. Will have a look at the PR soon.

**Comment by dlprows** [comment]
I tried making the change to test equal or subclass and ran into different problems thanks to me spending too much time in different languages.

I looked at the PR on this issue and I think that it could be done better. This PR relies on setting the deserializer on the `RefitSettings`, but I feel like it could be done based on the return type of the task instead.
With it on the `RefitSettings` you couldn't have multiple methods in the same interface that use different deserializers without having some messy code. 
I'm working on a code example right now

**Comment by dlprows** [comment]
I don't know of a way to reference it other than just leaving a link
https://github.com/dlprows/refit/commit/d34f02036f7bc75face75e0a4de43e52d2613544

I think doing something like this would be more extendable than adding the property to the RefitSettings. You can clearly annotate any methods that use a custom deserializer so that looking at the interface will give you all needed information. The PR attached to this issue right now relies on you setting the RefitSettings when you call `RestService.For` which makes it so you just have to know to setup your RefitSettings. This is made even less maintainable when you take into account that many times logging in will need a custom deserializer but all other network calls want to use the JSON deserializer.

The code I threw together also supports putting the annotation on an interface, and overriding it on a method, so that way if you want to always use a custom deserializer, you only have to put it on a bunch of interfaces instead of a ton of methods.

**Comment by MKuckert** [comment]
I also thought about a solution to customize the serialization process. I especially don't like how the default implementation pulls the whole stream into memory and doesn't deserialize the http stream directly. I like @dlprows implementation with annotations - it fit's the Refit-style of describing the interface. Using subclasses of HttpContent feels kind of weird and complicated.

**Comment by cfl777** [comment]
@dlprows Any progress with this? can I implement a deserializer, and how?

**Comment by onovotny** [comment]
As an update here, @bennor had a recent PR that eliminates reading the stream into memory an extra time. Happy to review an attribute-based deserlializer when it's ready @dlprows. I agree that using an attribute to declare it seems easier than setting up the settings each time as that puts the burden on the person wrapping the REST method and not the user of it.

**Comment by dlprows** [comment]
Sorry. I don't check github often enough. I've had custom deserializing by attribute since may of last year. I didn't realize other people would actually be interested in it.
I'll get things merged into my fork, and submit a pull request for it

**Comment by dlprows** [comment]
i'm not good at github, but here's the link for the pull request https://github.com/paulcbetts/refit/pull/345

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
