### ISSUE TITLE
What's with all these depedencies?

### ISSUE THREAD

**Issue by opcodewriter** [reactiveui/refit#444]
Can someone please shed some light why all these are needed?

![snip_20180221161233](https://user-images.githubusercontent.com/15019084/36484480-1c3cdcac-1722-11e8-99c9-488743e1a386.png)

Adding all that to my app doesn't look very good

**Comment by ahmedalejo** [comment]
@opcodewriter That´s probably because you using .netstandard 2.0 project.
And from you are showing the dependencies already existed as of Refit 4.0.1 in your projects and you are just updating them.

These are platform specific libs in the .netstandard libraries. 
For example runtime.**ubuntu**[PLATFORM]*System.Security.Cryptography.OpenSsl.
will not be included in your app for ios, android but will install in your project if it targets ubuntu.

If those where included in your app it could be over 200 MB

all this dependencies are platform specific libraries for platforms you might be targeting. In your case you´re targeting only **iOS** and **Android** so they won´t be include because their is already Xamarin.iOS and Xamarin.Android respectively for those.

They all include in the same nuget package so that you don´t need to search for platform specific packages.

Ex:

You install **Xamarin.Forms** package into your projects(pcl, android, iOS, UWP, MAC, netstandard, TIZEN, Gtk wpf e.t.c) and not Xamarin.Forms.Gtk, Xamarin.Forms.PCl

**Comment by opcodewriter** [comment]
@ahmedalejo Thanks for explaining it.

**Comment by opcodewriter** [comment]
@ahmedalejo On which platforms would those be inclued? On Linux? You mean if I were to develop a .NET (Mono I assume?) app on Linux and add Refit, those would be added?
