### ISSUE TITLE
When using an interface that is spread over multiple files (partial interfaces), Refit breaks

### ISSUE THREAD

**Issue by hansmbakker** [reactiveui/refit#471]
I'm writing a client for an API that has a lot of possible calls. I tried splitting the interface in multiple files by using `partial interface`.

Unfortunately, Refit seems to process code on a per-file basis and therefore generates duplicate code that 
then conflicts because it puts them in generated proxies having the same name.

`partial interface` was [mentioned as a possibility](https://github.com/paulcbetts/refit/issues/49#issuecomment-47830299), but it seems not to work?
 What do you suggest?

A workaround would be to put all code in one file but I'm not a fan of that, and otherwise I'll have to generate multiple interfaces resulting in multiple clients?

**Comment by wind-rider** [comment]
Yes, that is what I meant with 

> generate multiple interfaces resulting in multiple clients

Maybe the operation can be done faster using Roslyn?

E.g. using https://github.com/aarnott/CodeGeneration.Roslyn

**Comment by wind-rider** [comment]
Ok, I saw a mix of roslyn and mustache being used and thought there might be room for improvement. I understand that semantic level might be slower but I’m not sure that it will be forbiddingly slow.

I think this is also a point about whether Refit wants to completely support the c# language (which partial interfaces are a valid part of) or that it aims at being a tool that covers the most common usages.

**Comment by nhwilly** [comment]
@bennor Splitting them into multiple interfaces was the approach I was thinking about.  Glad I found someone who's doing this.  

I noticed that [RestLess](https://github.com/letsar/RestLess/blob/master/README.md) has done some benchmarks (shown in that link) and noted that there was some overhead to be eliminated with their technique (avoiding reflection, I believe).

But I have a **bunch** of endpoints and I was wondering if you thought it would be better to put them in one interface instead of breaking them out like you did (and I was planning).  

I guess I'm not sure where the performance bottleneck is.  But I don't want to build this whole thing out and then face refactoring all of it.

I totally get the sharing client thing, and I'm doing that.

Just wondering if you had any insight.

TIA

**Comment by Zexuz** [comment]
This is how I imagined it.
`IGithubApi .cs`
```csharp
    public interface IGithubApi : IGithubProjectCards, IGithubProjectColumns, IGithubRepoProject
    {
    }
```


`IGithubRepoProject.cs`
```csharp
    public interface IGithubRepoProject
    {
        [Headers("Accept: application/vnd.github.inertia-preview+json")]
        [Get("/repos/{ownerName}/{repoName}/projects")]
        Task<ProjectResource[]> GetProjects(string ownerName, string repoName);
    }

```
`IGithubProjectColumns.cs`
```csharp
    public interface IGithubProjectColumns
    {
        [Headers("Accept: application/vnd.github.inertia-preview+json")]
        [Get("/projects/{projectId}/columns")]
        Task<ColumnsResource[]> GetColumns(int projectId);
    }
```
`IGithubProjectCards.cs`
```csharp
    public interface IGithubProjectCards
    {
        [Headers("Accept: application/vnd.github.inertia-preview+json")]
        [Get("/projects/columns/{columnId}/cards")]
        Task<CardResource[]> GetCards(int columnIdd);

        [Headers("Accept: application/vnd.github.inertia-preview+json")]
        [Post("/projects/columns/cards/{cardId}")]
        Task<CardResource> ArchiveCard(int cardId);
    }
```

## Pros

- Better project/file structure. 
- Only needing one API
- Every endpoint can be in a separate interface.
- Less code

## Cons
- Slower performance (?)

**Comment by bennor** [comment]
The original request here is now possible: https://github.com/reactiveui/refit#interface-inheritance

**Comment by hansmbakker** [comment]
@bennor thank you!
