### ISSUE TITLE
Customizing RefitStubs.g.cs generatation

### ISSUE THREAD

**Issue by matheusneder** [reactiveui/refit#499]
I didn't find a way to customize RefitStubs.g.cs generatation with out editing mustache template in the Refit package. 

I'd like to propose a change to InterfaceStubGenerator.ExtractTemplateSource: It'll try get "GeneratedInterfaceStubTemplate.mustache" file from the project directory, if doesn't exists, get it from package directory or embbeded resource just as it is. 

This will bring the ability to the user customize RefitStubs.g.cs generatation for a single project scope. 

What do you think about? Is there another way already done in Refit to get this kind of customization?

**Comment by bennor** [comment]
Why do you need to customise it? And what are you planning on doing?

@onovotny recently merged a change that makes the generated classes partial, allowing for some customisation.

**Comment by matheusneder** [comment]
At first I'd like to throw customized exception types insteadof ApiException in case of HTTP status not 2xx.

**Comment by onovotny** [comment]
One concern here is that any external customizations to the template could be fairly brittle. The template today depends heavily on the internal implementation of the request builder. A PR like #494 changes the template significantly as part of the feature work. 

We don't have any current plans to formalize the contract since it is an implementation detail at this point to support AOT platforms. Otherwise, we'd have used dynamic ways to create the impls.

**Comment by matheusneder** [comment]
I understood, thanks for feeback.

I'm planning to use Refit in my projects which are most of all aspnet core microservices. As I commented, I'd like to make my clients throwing it's own exception types insteadof ApiException. To handle this, at first, I'll use a dynamic proxy (based on System.Reflection.DispatchProxy), so unfortunatelly, it will not support AOT platforms. 

Would you consider provide a way (on the generated client) to intercept the call? Should be events, something like OnBeforeCall, OnException, OnAfterCall. What do  you think about?

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
