### ISSUE TITLE
InterfaceStubGenerator.App seems to have nothing to do with other projects?

### ISSUE THREAD

**Issue by juepiezhongren** [reactiveui/refit#553]
I'm begging to see how BuildTask for stub creation is triggered while refit is referenced into my project.... And got confused that InterfaceStubGenerator.App seems to have nothing to do with other projects.

eager for answers

**Comment by Styxxy** [comment]
The build task is triggered because it is added before the Compile target in **refit.targets** (check the Refit project, targets folder) : https://github.com/reactiveui/refit/blob/master/Refit/targets/refit.targets .
-> Line 20 the task is imported.
-> Line 29 it is executed.

The InterfaceStubGenerator.App is actually and application for the unit test project, and you can use it yourself as well when you would like to debug refit. Apart from that, it is not used (nor included in the Refit package).

**Comment by onovotny** [comment]
@Styxxy is correct. Build tasks are much more difficult to debug as they can get stuck loaded in memory. The app just boostraps the same logic as the task to make testing easier.
