### ISSUE TITLE
Add support for custom serializers

### ISSUE THREAD

**Issue by stevewgh** [reactiveui/refit#566]
I have a requirement to integrate with an API which uses XML instead of JSON.

I noticed that a similar issue was raised (#83) a few years back but it was closed and the branch was deleted before the feature was added.

I'd like to add support for custom serializers as I would find it useful for my particular use-case but before I start looking at adding the support, is this something that the project maintainers would like adding?

**Comment by xljiulang** [comment]
[WebApiClient](https://github.com/dotnetcore/WebApiClient) support commit with xml content:
```c#
// PUT webapi/user  
// Body user的xml文本
[HttpPut("/webapi/user")]
ITask<UserInfo> UpdateUserWithXmlAsync([XmlContent] UserInfo user);
```

**Comment by benjaminhowarth1** [comment]
I like this. +1 from me

**Comment by stevewgh** [comment]
@benjaminhowarth1 well that makes at least two of us so I'll start taking a look to see what would be involved.

**Comment by Cheesebaron** [comment]
@benjaminhowarth1 @stevewgh please, use the reaction to +1. Adding a comment about +1 doesn't contribute anything to the discussion.

Currently the `BodySerializationMethod` isn't super extensible by the user. I guess we would need to find a better way to provide your own.

So maybe providing a serialization factory instead of having it be an enum would be an option.

I guess this factory should provide:
- Content-Type
- Serialized content as `HttpContent`

Similarly this should be done for deserilization where we should add some way to extend which deserializer should be used. This currently seems very hardly tied to this line of code: https://github.com/reactiveui/refit/blob/master/Refit/RequestBuilderImplementation.cs#L293

**Comment by stevewgh** [comment]
@benjaminhowarth1  @Cheesebaron pull request #571 covers the isolation of serialization and provides XML and JSON support. 

There are questions on how the ```BodySerializationMethod``` enum and other things mentioned in the PR would still work given the approach I've taken - so any feedback is welcome.

**Comment by onovotny** [comment]
The PR has been merged. Will bake on the MyGet feed for a bit and then be published to nuget. Thanks!

**Comment by stevewgh** [comment]
Hi @onovotny I've noticed an issue with the version published to MyGet which is related to the changes I've made. I think I've isolated the problem but I want to be able to recreate the issue in a test before submitting a fix. I'd recommend not publishing to nuget just yet.

**Comment by stevewgh** [comment]
Fixed with #590

**Comment by richbryant** [comment]
Sorry for the presumably silly question but how would one go about using this facility?

**Comment by stevewgh** [comment]
Answered here: https://github.com/reactiveui/refit/pull/571#issuecomment-453748711
