### ISSUE TITLE
Header attribute does not HtmlEncode() values

### ISSUE THREAD

**Issue by Flohack74** [reactiveui/refit#603]
Hello,

I would expect that the value of a Header() attribute would be encoded into Html entities automatically, since this is kind of required behaviour by spec. Can you comment on this, if this could be made?
Thx!

**Comment by bennor** [comment]
The specs don't prescribe a standard method for encoding non-ASCII characters (see [this answer on Stack Overflow](https://stackoverflow.com/a/48138818/14451) for more info).

That means we can't possibly guess at how the server will be expecting them. We also lean on .NET's built in `HttpClient`, and they don't auto-encode either.

That leaves you with two options:

1. Find out what your server is expecting and encode manually. I expect because there's no standard here, you'll need to decode manually at the server too, if you own it.
2. Try raising an issue with Microsoft about the .NET `HttpClient`.

If you go with the more sensible option of doing it yourself, I'd recommend URL encoding (with `Uri.EscapeDataString()`) rather than HTML encoding. I don't think HTML encoding will automatically fix non-ASCII characters.

Lastly, if you're worried about ampersands, and other special characters in HTML, they're not a problem in headers because headers aren't HTML.
