### ISSUE TITLE
Refit ignores the EnumMember attribute for enums inside classes

### ISSUE THREAD

**Issue by Sergio0694** [reactiveui/refit#617]
This is related with #459 and #502.
The `EnumMember` attribute is now correctly used when directly passing enums as parameters to a Refit method in an interface, but it seems to be ignored when the enum in question is inside a container class.
Here's an example:

```csharp
public enum TestEnum
{
    [EnumMember(Value = "bla")]
    BLA
}

public class TestClass
{
    [AliasAs("value")]
    public TestEnum Value { get; set; }
}

public interface IService
{
    [Get("/foo")]
    Task FooAsync(TestClass value);
}
```

Calling the `FooAsync` method here ends up using the URI `/foo?value=BLA` instead of `/foo?value=bla`.
Of course, this works perfectly fine if the enum is passed directly as a parameter to a Refit method instead.

Note: The `EnumMember` attribute also doesn't work when used for an enum passed as an array, but I'll open a separate issue for that.

**Comment by jayhenn** [comment]
It appears that when Refit is formatting the `TestClass.Value` property as a URL query parameter, the third argument passed to `DefaultUrlParameterFormatter.Format(object parameterValue, ICustomAttributeProvider attributeProvider, Type type)` is the `TestClass` type. Since `TestClass` is not an `Enum`, the code does not attempt to use the `EnumMemberAttribute` for any formatting.

I believe the fix would be to leverage the type of the `parameterValue` itself to format the `parameterValue`. In this case, the type of `parameterValue` is `TestEnum`.

Admittedly I've never contributed any code changes on GitHub, and I don't have the time right now, but I think the fix would look something like this:
```csharp
public class DefaultUrlParameterFormatter : IUrlParameterFormatter
{
    static readonly ConcurrentDictionary<Type, ConcurrentDictionary<string, EnumMemberAttribute>> EnumMemberCache
        = new ConcurrentDictionary<Type, ConcurrentDictionary<string, EnumMemberAttribute>>();

    public virtual string Format(object parameterValue, ICustomAttributeProvider attributeProvider, Type type)
    {

        // See if we have a format
        var formatString = attributeProvider.GetCustomAttributes(typeof(QueryAttribute), true)
            .OfType<QueryAttribute>()
            .FirstOrDefault()?.Format;

        EnumMemberAttribute enummember = null;
        if (parameterValue != null)
        {
            var parameterType = parameterValue.GetType();
            if (parameterType.IsEnum)
            {
                var cached = EnumMemberCache.GetOrAdd(parameterType, t => new ConcurrentDictionary<string, EnumMemberAttribute>());
                enummember = cached.GetOrAdd(parameterValue.ToString(), val => parameterType.GetMember(val).First().GetCustomAttribute<EnumMemberAttribute>());
            }
        }

        return parameterValue == null
            ? null
			: string.Format(CultureInfo.InvariantCulture,
							string.IsNullOrWhiteSpace(formatString)
								? "{0}"
								: $"{{0:{formatString}}}",
							enummember?.Value ?? parameterValue);
    }
}
```

Lastly, I don't have the time to see where/how this particular method is being used, and don't know if this would break anything, but seemed to work for my use case.
