### ISSUE TITLE
Receive Cookie on login

### ISSUE THREAD

**Issue by pepobit** [reactiveui/refit#630]
Hello,

The login method I have to call returns a cookie to use with the other calls. How can I keep the cookie received in the login rest method?

Thanks.

**Comment by bennor** [comment]
This will happen automatically if you reuse the same `HttpClient` for all your calls (which seems wrong, but is actually the way you're supposed to use `HttpClient`).

You have a few options here:

- If you're using ASP.NET core, and you only have one API interface, this will happen automatically when you use `services.AddRefitClient<IYourApi>()` to register your api.
- otherwise, you'll want to create your service instance using the `RestService.For<T>()` method that takes an `HttpClient` and use a singleton `HttpClient` (either registered with a singleton lifetime in your DI container, stored in a static variable, or anything else that causes every API service instance to reuse the same object).
