### ISSUE TITLE
Pass CancellationToken to IContentSerializer

### ISSUE THREAD

**Issue by ysmoradi** [reactiveui/refit#644]
I'm implementing IContentSerializer interface and in my implementation, I've no access to cancellation token. Could you please provide it too? Thanks in advance.

**Comment by Styxxy** [comment]
This is pretty straightforward to implement, though it would be a breaking change due to a public interface that will be changed.

Another option would be to create a derived interface that adds this option, and we check first for the derived interface and if provided class is not of that type, we use the base interface. It would feel a little bit more "dirty", though this would be a solution to not introduce any "breaking" change (for people who have written their own IContentSerializer).

@onovotny Your two cents?

**Comment by ysmoradi** [comment]
I prefer 2nd approach. Note that there is a real need for content serialization, so it worth its cost

**Comment by ysmoradi** [comment]
But I think it's hard to find a name for new interface!

**Comment by Styxxy** [comment]
`IContentSerializerWithCancellation` 😋

**Comment by onovotny** [comment]
Using a second interface seems like the best option at the moment.

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
