### ISSUE TITLE
What is proper lifetime of the Client created by RestService.For<>()?

### ISSUE THREAD

**Issue by Hooch180** [reactiveui/refit#656]
Hello.
I'm using this library for simple communication with REST service from my Windows Service.
The communication with service is needed only from time to time (every few hours) and each time consists of 10-100 requests.

Should I create new client using RestService.For<>() for every "burst" of activity? Or once for lifetime of whole Windows Service (weeks if not months at a time)?

In short. What is proper lifetime of ReserService Client?

**Comment by bennor** [comment]
In general, you should use the `Refit.HttpClientFactory` package, and not worry about it too much. There's a good breakdown of why here, and it's worth taking a few minutes to read it: https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests

However, if you don't have using `HttpClientFactory` as an option (and you may not in a Windows Service), it boils down to whether you're more concerned about the risk of:

- socket exhaustion (through creating too many `HttpClient` instances in a short space of time)
- not picking up DNS changes (caused by using a static `HttpClient` instance, which caches DNS internally)

If all you're doing is making a few hundred requests in a burst every few hours, I doubt you're at risk of socket exhaustion. And if you're only ever hitting the same API, DNS changes may not be a big problem either. So it probably doesn't matter at all in your situation.

If it were me, I would probably create a new instance for each burst, then throw it away. I don't think there's any value in making it static if you're keeping it alive for weeks/months at a time.
