### ISSUE TITLE
[BUG] Refit doesn't trap all exceptions and wrap with ApiException

### ISSUE THREAD

**Issue by CreepyGnome** [reactiveui/refit#719]
Currently it is stated, not in main readme/docs BTW but in issues, you only need to catch ApiException from a Refit call to a rest service. However for most of the common issues that can occur on any network call including rest services it doesn't ever throw it. Instead, it throws HttpRequestException which is not very useful at all as HttpRequestException has no status code, and its inner exception is usually not useful as well as it probably doesn't have a status code either. 

Why not capture all exceptions and guarantee that you only throw ApiExceptions and set its inner exception if there is one to the exception it caught, ie HttpRequestException.

If you google how to get status code from HttpRequestException you will see all the "You're doing it wrong" SO's and other posts.  The problem with that is if that is doing it wrong then anyone who exposes that exception is also doing it wrong. And I know I can have Refit return the HttpRequestMessage, however, I would argue that defeats a lot of the reasons to even use Refit to get a clean interface.

**Steps To Reproduce**
User Refit to call an API while your network is down to trigger a host cannot be reached issue and you will not get an ApiException.

**Expected behavior**
That any error conditions and exceptions that occur from calling using Refit to call services that it only throws its one ApiException that will include an inner exception is there is one.

**Environment**
Any

**Additional context**
None.

**Comment by bennor** [comment]
I tend to agree - I've run into this issue myself. There are a couple of issues with catching these exceptions and raising an `ApiException` though:

1. There isn't a status code for the different error conditions that could cause an `HttpRequestException`. So that leaves us with two options:
    * make `ApiException.StatusCode` nullable (a breaking change)
    * don't set it (effectively setting it to `(HttpStatusCode)0`, which is an invalid value, and also potentially a breaking change for some consumers
    * add a new exception for requests (e.g. `ApiRequestException`), which sort of defeats the purpose
1. the fact that there are many different reasons for the request to fail mean that there's data in the original exception that may need to be processed by downstream callers, so they might as well catch the original exception in this instance

I get that the fact we don't return a single exception type for any API request failure is inconsistent, but I'm not really sure what the best approach for fixing this would be at this point. Perhaps just making `StatusCode` nullable and forcing people to fix the _small_ breaking changes in error handling code is the best course of action? Another option could be to subclass `ApiException` to `ApiRequestException` and `ApiResponseException` for anyone who wants to handle the different cases, but that would probably be overkill.

Open to suggestions on this one. Thoughts, @onovotny & @anaisbetts?

**Comment by CreepyGnome** [comment]
While having one exception to rule them all, I personally rather have predictability and similar contracts with two exceptions that Refit could through as opposed to how it is now.  I think I would rather retain as much of the fidelity of the original data as possible. 

I rather have a solution that doesn't introduce any breaking changes. I would think having ApiRequestException and ApiException is a good and safe compromise.  Then anything that does have a real status code goes into ApiException, and the rest could be the ApiRequestException that has no status code on it both should have their inner exception as the would-be HttpRequestException, or other related ones potentially.  That should cover those corner cases where there is no status code we will know exactly when there isn't one this way and we can dig into the inner exception to decide how we want to handle it and map it to a status code if needed.

**Comment by onovotny** [comment]
If we introduce `ApiRequestException`, it could derive from `ApiException` and not change behavior, right? That could be the best option.

**Comment by CreepyGnome** [comment]
IMO I don't think ApiRequestException should extend ApiException as it would be misleading as it should not have the StatusCode and if it extends the other it will always be 0. Other than that it would have all the other properties though, but it's not violating Dry as while it is duplicated it has a different purpose to change so should be separated.  ApiException is for all things refit can catch that have a StatusCode and ApiRequestException is for all those things that don't get StatusCodes.

If it could safely be extended then it could also just be removed IMO as then we are saying we can make it fit into ApiException itself which @bennor explained isn't a good idea due to breaking changes or bad invalid status code always being zero.

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
