### ISSUE TITLE
Package support Polly? If not, can we support it?

### ISSUE THREAD

**Issue by ghd258** [reactiveui/refit#771]
Package support Polly? If not, can we support it?

**Comment by Cheesebaron** [comment]
Can you elaborate please? I have no idea what you are asking about here.

**Comment by ghd258** [comment]
https://github.com/App-vNext/Polly   or Microsoft.Extensions.Http.Polly

services.AddHttpApiTypedClient<IDemoApi>(config => { })
    .ConfigurePrimaryHttpMessageHandler(() => new HttpClientHandler() { UseProxy = false })
    //fallback       
     .AddPolicyHandler(Policy<HttpResponseMessage>.Handle<Exception>().FallbackAsync((ctx, ct) =>
     {
            return Task.FromResult(new HttpResponseMessage
            {
                Content = new StringContent("fallback"),
                StatusCode = HttpStatusCode.OK
            });
      }, async (b, ctx) =>
      {
          await Task.CompletedTask;
      }));

**Comment by ghd258** [comment]
Polly is a .NET resilience and transient-fault-handling library that allows developers to express policies such as Retry, Circuit Breaker, Timeout, Bulkhead Isolation, and Fallback in a fluent and thread-safe manner

**Comment by onovotny** [comment]
Not sure what you need here. You can wrap your calls to the API with Polly and have it retry. Plenty of people use it that way.

**Comment by ghd258** [comment]
Can you give me an example of a demo

**Comment by onovotny** [comment]
Use/configure Polly normally. Then put the call to the refit-generated interface in the `ExecuteAsync` part:
https://github.com/App-vNext/Polly#step-1--configure

**Comment by onovotny** [comment]
Closing as a question and by-design. This scenario is already supported.

**Comment by andrekiba** [comment]
Hello and thanks in advance! Yes, you can put the refit-generated call inside the Polly `ExecuteAsync `but what about the case in which Polly and Refit are used with HttpClientFactory? For example: is there a way to setup the Polly `Context` before each call with Refit?
https://github.com/App-vNext/Polly/wiki/Keys-And-Context-Data
I didn't find a way to manage this.  
In `Controllers` for example you inject the refit-generated interface (and it is amazing) but at this point you can't setup the `Context` because you can't access the underlying http request.
Polly provides the `request.SetPolicyExecutionContext(context);` but we can't use it. 
https://github.com/App-vNext/Polly/wiki/Polly-and-HttpClientFactory#use-case-exchanging-information-between-policy-execution-and-calling-code

**Comment by onovotny** [comment]
You can add a get property of type HttpClient on your interface to get to the current instance. Shoes that help?

**Comment by andrekiba** [comment]
I don't think so but could you please explain?
