### ISSUE TITLE
[BUG] SystemTextJsonContentSerializer is always sending 8192 bytes

### ISSUE THREAD

**Issue by acgritt** [reactiveui/refit#870]
**Describe the bug**
The SystemTextJsonContentSerializer is always sending 8192 bytes even when data is less than this and is then leaking data from adjacent memory in the request.

**Steps To Reproduce**
Have not reproduced this outside of my project. I found it with Fiddler when running locally.

**Expected behavior**
Only the data being sent should be sent in the body.

**Screenshots**
From Fiddler Syntax View
![image](https://user-images.githubusercontent.com/10471937/77697560-10b34280-6f7d-11ea-890b-5f2f28e6b6d9.png)

**Environment**
- OS:       Windows 10
- Version:   5.1.27

**Additional context**
This was found after upgrading to 5.1.27 where before I had a custom IContentSerializer performing this work using the following to serialize:
`var content = new StringContent(JsonSerializer.Serialize<T>(item, _jsonSerializerOptions.Value), Encoding.UTF8, MediaTypeNames.Application.Json);`

**Comment by Sergio0694** [comment]
Hey @acgritt, would you mind testing this out with a new pre-release build that includes the fixes done in https://github.com/reactiveui/refit/pull/866, and see if the issue still persists for you? If it does, could you create a minimal repro or a simple test method I could use to investigate this?
Thanks! 😊

**Comment by acgritt** [comment]
I will do so and update later today.

**Comment by acgritt** [comment]
I tested and 5.1.50 does resolve the issue.

**Comment by Sergio0694** [comment]
That's great, glad to hear that! 😄

cc. @clairernovotny looks like the new serializer is fine at this point 🎉

**Comment by martincostello** [comment]
I think there's a scenario related to this bug that isn't fixed by #866 in version 5.1.54.

I have some end-to-end tests in an application that perform an HTTP PUT of some JSON to another API for a combination for different input values and _sometimes_ the requests fail with an HTTP 400 where they previously worked.

If also tried with and without buffering enabled on the `[Body]` attribute of the parameter, but that doesn't help either. The intermittent nature of the error suggests to me that maybe there's an issue with the pooled buffer reuse causing later requests to be corrupted and being sent with invalid content.

Looking at the payloads with Fiddler, there appear to be leading and trailing garbage characters being added to the payload. Here's an example of a "good" request body and a "bad" request body:

## Good

```
{"ConsumerId":"2854854","CustomerCity":"London","CustomerName":"John","OrderId":"f7rkmoyqi0oxckd8wpkgia","RestaurantId":"141479"}
```

## Bad

```
B8
{"RatingCode":"10988615jphveggggxubyhfaekyyk","ConsumerId":2854854,"OrderId":"f7rkmoyqi0oxckd8wpkgia","CustomerComments":"The food was very nice.","Delivery":4,"Quality":5,"Service":6}
0


```

**Comment by martincostello** [comment]
Comparing two requests, it seems that a "good" one sends `Transfer-Encoding: chunked` and is encoded, where as the "bad" ones send `Content-Length` instead.

**Comment by martincostello** [comment]
On further investigation, this is a different issue. I'll open a PR with a proposed fix shortly.

**Comment by martincostello** [comment]
> On further investigation, this is a different issue. I'll open a PR with a proposed fix shortly.

#885
