### ISSUE TITLE
InvalidOperationException thrown when using constant string instead of string literal for Refit HttpAction/Route attributes

### ISSUE THREAD

**Issue by Wind010** [reactiveui/refit#911]
**Describe the bug**
InvalidOperationException thrown when using constant string instead of string literal for Refit HttpAction/Route attributes.

**Steps To Reproduce**
```csharp
    public interface IApi
    {
        public const string Some_Route = "/some/route/";

        [Post(Some_Route )]
        [Headers("Content-Type: application/json")]
        Task<ApiResponse<MyResponse>> DoSoemthing(SomeType someType);;
    }

```

```sh
System.InvalidOperationException: IRecommendedProductsApi doesn't look like a Refit interface. Make sure it has at least one method with a Refit HTTP method attribute and Refit is installed in the project.
```

**Expected behavior**
No exception should be thrown.  Constant string validated successfully as route.

**Screenshots**

**Environment**

- OS:       Windows 10 x64
- Device:   PC
- Version:   5.1.67
- Working Version: NA

**Additional context**

**Comment by jdluzen** [comment]
Can confirm this as well.

**Comment by josefblaha** [comment]
It seems that using constants is deliberately disabled (see [InterfaceStubGenerator.cs#L299](https://github.com/reactiveui/refit/blob/master/Refit.Tests/InterfaceStubGenerator.cs#L299) in tests, added in #67). Is there any reason that? Except from being regarded as "weird" and "dumb"?

Use case: We have an internal API and a client library with Refit. We want define URL paths in one place; share them between controller actions and the client definition.

@bennor?

**Comment by bennor** [comment]
To avoid using the slower, semantic form of analysis, we make a few assumptions to determine we've found a Refit attribute and not some other (admittedly unlikely) attribute called `Get`. 

IIRC if the parameter is a constant, we can't tell it is a string, which was one of the criteria we use to check the attribute is ours.

However, maybe the worst that happens if we get a few false positives is adding some unused generated classes to your project. 

I've wondered for a while, based on the number of people that request this, if we should just remove that check (or, better, allow constants as well as strings).

I'm not really involved enough to feel comfortable making a call though.

@clairernovotny?

**Comment by clairernovotny** [comment]
🤷‍♀️ at this point, if it can be made to work, with unit tests to match, then I'd be for it. We do need to have tests for the error case though when it's simply invalid.

**Comment by jamiehowarth0** [comment]
@bennor @clairernovotny I'm happy to take a look at this cause it's come across my path recently.

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
