### ISSUE TITLE
[BUG] Blazor WebAssembly

### ISSUE THREAD

**Issue by ekjuanrejon** [reactiveui/refit#984]
**Describe the bug**
Blazor WebAssembly throws AccessTokenNotAvailableException

Create a Refit client that requires authentication. When using refit alongside Blazor AuthorizationMessageHandler it throws and error. It does not get the JWT from the logged in user

**Comment by nicostouch** [comment]
@ekjuanrejon can you provide more information on how the Refit client is being instantiated in this case and how the HttpClient is configured? 

The problem seems likely to be happening in an area adjacent to Refit rather than Refit itself as AuthorizationMessageHandler is just a DelegatingHandler being invoked by the underlying HttpClient and that throws AccessTokenNotAvailableException when its IAccessTokenProvider can't get an access token.  If AuthorizationMessageHandler is throwing that exception it must mean it's not happy with the DI registrations somewhere along the way.

**Comment by ekjuanrejon** [comment]
@james-s-tayler 
sorry for the late response and back at it

I am following this doc
https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-5.0#custom-authorizationmessagehandler-class

**Comment by james-s-tayler** [comment]
Hmm. Looking at this it seems unlikely to be a problem with Refit itself. People often have problems with either how they've configured HttpClient, or DI, or the JSON serialization options in RefitSettings etc, and not Refit itself. It's always a good idea to see try eliminate Refit as a factor by keeping everything else the same and using HttpClient directly and seeing how that behaves. I suspect you would likely get the same error.

Reading the documentation and the error you're getting it seems like somewhere something is configured wrong. The code snippet you've pasted looks perfectly reasonable, but I can imagine scenarios like configuring a single Refit client with those settings and accidentally using it to call both api endpoints that require auth and api endpoints that don't require auth (like a user login screen etc) and then getting that exception when you try to access the login screen because you have configured it to always try and attach an access token and in the case of an unauthenticated user it wouldn't have one.
